/**
* DealersAndVehicles
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param success 
 * @param message 
 * @param totalMilliseconds 
 */
data class AnswerResponse (
    val success: kotlin.Boolean? = null,
    val message: kotlin.String? = null,
    val totalMilliseconds: kotlin.Int? = null
) {

}

