/**
* DealersAndVehicles
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.VehicleAnswer

/**
 * 
 * @param dealerId 
 * @param name 
 * @param vehicles 
 */
data class DealerAnswer (
    val dealerId: kotlin.Int? = null,
    val name: kotlin.String? = null,
    val vehicles: kotlin.Array<VehicleAnswer>? = null
) {

}

