/**
* DealersAndVehicles
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param vehicleId 
 * @param year 
 * @param make 
 * @param model 
 * @param dealerId 
 */
data class VehicleResponse (
    val vehicleId: kotlin.Int? = null,
    val year: kotlin.Int? = null,
    val make: kotlin.String? = null,
    val model: kotlin.String? = null,
    val dealerId: kotlin.Int? = null
) {

}

